site_name: Octopus Sensing
repo_url: https://github.com/octopus-sensing/octopus-sensing
edit_uri: ""
site_author: "Nastaran Saffaryazdi"
site_description: ""
site_dir: docs_build/

theme:
  name: readthedocs
  prev_next_buttons_location: none

markdown_extensions:
  - toc:
      permalink: True

plugins:
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        selection:
          docstring_style: numpy
          filters:
            - "!^_"  # exlude all members starting with _
        rendering:
          show_root_heading: yes
          show_if_no_docstring: yes
          members_order: source
          show_source: True

nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - API Reference: api-reference.md
  - Development: development.md
