site_name: Octopus Sensing
repo_url: https://github.com/nastaran62/octopus-sensing/
edit_uri: ""
site_author: "Nastaran Saffaryazdi"
site_description: ""
site_dir: docs_build/

theme:
  name: readthedocs
  prev_next_buttons_location: none

markdown_extensions:
  - toc:
      permalink: True

plugins:
- mkdocstrings:
    default_handler: python

nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - API Reference: api-reference.md
  - Development: development.md
